"""Add uniqueness constraint

Revision ID: 40a14634c7ef
Revises: 
Create Date: 2024-01-18 00:03:31.320632

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '40a14634c7ef'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_skills_skill_name', table_name='skills')
    op.create_index(op.f('ix_skills_skill_name'), 'skills', ['skill_name'], unique=True)
    op.drop_index('ix_tools_tool_name', table_name='tools')
    op.create_index(op.f('ix_tools_tool_name'), 'tools', ['tool_name'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tools_tool_name'), table_name='tools')
    op.create_index('ix_tools_tool_name', 'tools', ['tool_name'], unique=False)
    op.drop_index(op.f('ix_skills_skill_name'), table_name='skills')
    op.create_index('ix_skills_skill_name', 'skills', ['skill_name'], unique=False)
    # ### end Alembic commands ###
